### ISSUE TITLE
Front Page Slideshow Feature Request

### ISSUE THREAD

**Issue by RalfKerkhoff** [gjr-osweb/libratus#1]
Hi,
it would be great if the frointpage slideshow has an extra option to specify a folder for the sildeshow images.
If the image size (for those with limited server quota) is not that large the images expanded to full screen look ugly.
If the slideshow images can be taken from a specific folder, this folder could have a small amount of large sized images.

**Comment by gjr-osweb** [comment]
Already implemented :)
