### ISSUE TITLE
improvement of password page

### ISSUE THREAD

**Issue by vincent3569** [gjr-osweb/libratus#10]
hi

on album page, you offer navigation between album (prev, next) : but if you have a protected album, it breaks the navigation.
could you improve password page, to allow navigation between albums when you are on protected one (you can be on password form to access to protected album and wish to go to next of return on previous album) ?

maybe this improvement is for image page too.

**Comment by gjr-osweb** [comment]
I looked into this and cannot do it without modifying the core password form function to store the current object. All it carries over is the redirect url, not the actual album object, sorry.
