### ISSUE TITLE
issue with sized thumbnails

### ISSUE THREAD

**Issue by vincent3569** [gjr-osweb/libratus#13]
I am not sure it is an issue or not...

on album page, with Justified-Gallery : how works Justified-Gallery's functionality to display different thumbnails for different viewport size?
should the theme create all needed thumbnails suffix with _m, _n, _z,...)?
is there an request (with ajax ?) to load the good thumbnail for the current viewport ?
in all case, I can't see anything about these sized thumbnails in your theme.

**Comment by gjr-osweb** [comment]
The theme creates the thumbnail set in options just like any theme.  Default is 300 which is big enough for any output from the justifiedgallery options set (row-height).

I do not want to make this overly-complicated for this theme.
