### ISSUE TITLE
feature request for slideshow

### ISSUE THREAD

**Issue by vincent3569** [gjr-osweb/libratus#14]
hi
on album page, you used swipebox : can you use it to make the slideshow (unfortunatly, colorbox is not realy responsive)

**Comment by gjr-osweb** [comment]
Swipebox is great on touch devices, I like it that way for that reason.

I have done some custom things to improve the cycle2 slideshow.  Did you check that out?

**Comment by vincent3569** [comment]
hi
I tried cycle2 slideshow.
some comments about it on mobile device (my iphone):
- the font for title is too big
- after picture is displayed (seems to be displayed on the larger of the screen), picture seems to be scalled, and a empty space appears on the right side
