### ISSUE TITLE
full screen full resolution

### ISSUE THREAD

**Issue by mindhaq** [gjr-osweb/libratus#17]
I would love it when this great theme would display full screen images in their full resolution, using the complete browser size.

currently, only 800px images are used, and when I change that setting in the theme options to e.g. 1200, it's not saved but reset to 800px again.

**Comment by vallka** [comment]
Hi mindhaq
I've added a colorbox plugin support to the theme - it is doing not exactly what you want, but it is even better, I think :)

Please see an example here:
http://photo.vallka.com/2015-05%20-%20Loch%20Tummel/IMGP0022.jpg

Jut hope the author will accept my addition

Vallka
