### ISSUE TITLE
Always show name of sub-album on thumbnail

### ISSUE THREAD

**Issue by ghost** [gjr-osweb/libratus#19]
Fantastic theme by the way!

I have a hierarchy of photos in albums and sub-albums. Sometimes one album will only have sub-albums. The problem with this theme is that unless I hover my mouse over the thumbnail of the sub-album I don't know what it is.

For example:

Travel >
  Country 1 >
     City 1 >
      ...
  Country 2 >
     City 1 >
      ...
  Country ... >
     City 1 >

etc.

What I need I for the name of sub-albums to always be shown. So in the above example it would be great if the thumbnail always had the caption "Country 1" and "City 1" etc...

**Comment by gjr-osweb** [comment]
In the theme options there is a box to put curtom CSS.  Paste this is this box and save:

<code>
.gallery-thumbs-large.justified-gallery>a>.caption, .gallery-thumbs-large.justified-gallery>div>.caption {display:block;opacity:0.7;}
</code>

**Comment by ckfreeman** [comment]
Is there a way to do this within select albums for image thumbnails as well? That is, show either the title or the caption on top of or under the thumbnail. I have some videos in my gallery but the thumbs are essentially indistinguishable from pictures. Id really like to be able to display, a title or a caption within select albums. Unfortunately I do not know enough about CSS to do this myself. Thanks
