### ISSUE TITLE
Sidebar Menu - Feature Request

### ISSUE THREAD

**Issue by RalfKerkhoff** [gjr-osweb/libratus#2]
Hi,
maybe it is possible that the news categories can be displayed in the sidebar menu.
At the moment the sidebar only shows the main category: News.

**Comment by gjr-osweb** [comment]
You mean the off-canvas menu that slides in?

**Comment by gjr-osweb** [comment]
![image](https://cloud.githubusercontent.com/assets/3648260/6398528/d3b80d84-bdb1-11e4-9be2-dfea26e38a92.png)

**Comment by RalfKerkhoff** [comment]
Hi 
yes I mean the off-canvas menu.
