### ISSUE TITLE
Home page script also displays protected images

### ISSUE THREAD

**Issue by michgagnon** [gjr-osweb/libratus#27]
I removed the image-display code on the home page, using a tip provided by Fretzl on the Zenphoto support forum: http://www.zenphoto.org/support/topic.php?id=1409305  (I actually put "$_zp_page == 1000" instead). 
Apart from personal preferences, there is a bug that allows the script to display photos from published but password-protected albums too, even for unlogged users. 

P.S. I will probably use the image rotation trick in individual folders, though.

**Comment by gjr-osweb** [comment]
I think this would be a bug with the getImageStatistic function, not the theme. Best submit a ticket with Zenphoto so we can look at it.
