### ISSUE TITLE
SlideShow in page

### ISSUE THREAD

**Issue by mikysal78** [gjr-osweb/libratus#32]
on version Zenphoto 1.4.12 
in single page "View Slideshow" is page blank, 

the html is in pastebin http://pastebin.com/NRRUB18S

**Comment by fretzl** [comment]
There has been an issue with the slideshow in 1.4.12 that has been fixed in the Zenphoto [Support build](https://github.com/zenphoto/zenphoto/archive/master.zip)
Please try that.
