### ISSUE TITLE
issue with login

### ISSUE THREAD

**Issue by vincent3569** [gjr-osweb/libratus#5]
hi

login doesn't work : I am redirected to password page, with only password input.

**Comment by gjr-osweb** [comment]
I think I already fixed this Vincent please verify master.

**Comment by vincent3569** [comment]
sorry, I don't use master before create all my tickets :-(
it works, ...but after login, we stay on password page.
according to me, we should be redirected to home page

**Comment by gjr-osweb** [comment]
If you use the redirect parameter you take away the fact that ZP will redirect to the current object forcing the login.  As I have it now, if you request a password protected object, you get the login, then after successful login you are redirected back to that object you were trying to access.

I have setup a check so if you directly access the login, say through the login link from the user_login_out plugin, it will notify that you are logged in afterword and give you a link to home.

See what you think.
