### ISSUE TITLE
improvement of homepage slideshow

### ISSUE THREAD

**Issue by vincent3569** [gjr-osweb/libratus#6]
hi

can you allow to use a specific album to make homepage slideshow, and maybe, allows some options to resize (or not) pictures?
for example, I wish to create a dynamic album with tagued pictures with slideshow tag (best pictures with horizontal format), and I don't want the pictures to be resized because of the degradation of image quality.

**Comment by vincent3569** [comment]
hi
I saw the improvement : very nice.
there is an issue : dynamic albums are not displayed, so we can't choose them for homepage slideshow

**Comment by gjr-osweb** [comment]
Dynamic albums are showing for me:

![image](https://cloud.githubusercontent.com/assets/3648260/6416615/f6cdcc30-be6c-11e4-90b2-df717f1bebc5.png)

**Comment by vincent3569** [comment]
ok, my dynamic albums was unplubished...

according to me you should allow to use unplubished in homepage slideshow
in my case I want to display a slideshow with my portfolio (unpublished dynamic album).
I am obliged to have a first unpublished level of album and then, my published dynamic album
